// Mocks generated by Mockito 5.4.4 from annotations
// in pokemon_app/test/data/repositories/pokemon_repository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokemon_app/data/data.dart' as _i2;
import 'package:pokemon_app/domain/datasources/pokemon_datasource.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonDetailResponse_0 extends _i1.SmartFake
    implements _i2.PokemonDetailResponse {
  _FakePokemonDetailResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonDatasource extends _i1.Mock implements _i3.PokemonDatasource {
  MockPokemonDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.PokemonResponse>> getPokemons({
    int? offset = 0,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemons,
          [],
          {
            #offset: offset,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i2.PokemonResponse>>.value(
            <_i2.PokemonResponse>[]),
      ) as _i4.Future<List<_i2.PokemonResponse>>);

  @override
  _i4.Future<_i2.PokemonDetailResponse> getPokemonById({required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonById,
          [],
          {#id: id},
        ),
        returnValue: _i4.Future<_i2.PokemonDetailResponse>.value(
            _FakePokemonDetailResponse_0(
          this,
          Invocation.method(
            #getPokemonById,
            [],
            {#id: id},
          ),
        )),
      ) as _i4.Future<_i2.PokemonDetailResponse>);

  @override
  _i4.Future<List<_i2.PokemonFilterResponse>> getFilters({
    required String? endPoint,
    int? offset = 0,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFilters,
          [],
          {
            #endPoint: endPoint,
            #offset: offset,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i2.PokemonFilterResponse>>.value(
            <_i2.PokemonFilterResponse>[]),
      ) as _i4.Future<List<_i2.PokemonFilterResponse>>);

  @override
  _i4.Future<List<_i2.PokemonResponse>> getPokemonsByFilter({
    required String? endPoint,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonsByFilter,
          [],
          {
            #endPoint: endPoint,
            #name: name,
          },
        ),
        returnValue: _i4.Future<List<_i2.PokemonResponse>>.value(
            <_i2.PokemonResponse>[]),
      ) as _i4.Future<List<_i2.PokemonResponse>>);

  @override
  _i4.Future<void> toggleFavorite(_i2.PokemonEntity? pokemonEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [pokemonEntity],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isPokemonFavorite(int? pokemonId) => (super.noSuchMethod(
        Invocation.method(
          #isPokemonFavorite,
          [pokemonId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.PokemonEntity>> loadFavoritesPokemons({
    int? limit = 10,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadFavoritesPokemons,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.PokemonEntity>>.value(<_i2.PokemonEntity>[]),
      ) as _i4.Future<List<_i2.PokemonEntity>>);
}
